# Site settings
title: Getting Started Samples for Solace Messaging API for Java (JCSMP)
email: info@solacesystems.com
description: > # this means to ignore newlines until "baseurl:"
  These tutorials will get you up to speed and sending messages with Solace technology as quickly as possible.
baseurl: "/solace-samples-java" # the subpath of your site, e.g. /blog
url: "solacesamples.github.io" # the base hostname & protocol for your site
repository: https://github.com/SolaceSamples/solace-samples-java

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /docs/:path/
