# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Getting Started Samples for Solace Messaging API for Java (JCSMP)
email: info@solacesystems.com
description: > # this means to ignore newlines until "baseurl:"
  These tutorials will get you up to speed and sending messages with Solace technology as quickly as possible.
baseurl: "/solace-samples-java" # the subpath of your site, e.g. /blog
url: "solacesamples.github.io" # the base hostname & protocol for your site
repository: https://github.com/SolaceSamples/solace-samples-java

twitter:
  username: "@github"
github_username:  mdspielman

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /docs/:path/
